---
# tasks file for Pure_Set_Host_Personality
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Gather capacity report
    shell: sshpass -p "pureuser" ssh -o StrictHostKeyChecking=no pureuser@flasharray1 "purehost setattr {{ Hostname }} --personality {{ personality }} "
    register: op
    ignore_errors: true
  - debug:
      var: op
  - set_fact:
      status_code: 2
      response_message: "{{ op.stderr }}"
    when: op is failed
  - set_fact:
      response_message: "The personality of the host-{{ Hostname }} set to {{ personality }}\n{{ op.stdout }}"
    when: op is success

