---
# tasks file for Pure_List_Hardware
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Gather capacity report
    shell: sshpass -p "pureuser" ssh -o StrictHostKeyChecking=no pureuser@flasharray1 "purehw list --spec"
    register: op
    ignore_errors: true
  - debug:
      var: op
  - set_fact:
      status_code: 2
      response_message: "{{ op.stderr }}"
    when: op is failed
  - set_fact:
      response_message: "Following is the hardware list with specs\n{{ op.stdout }}"
    when: op is success

