---
# tasks file for Pure_Rename
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Gather capacity report
    shell: sshpass -p "pureuser" ssh -o StrictHostKeyChecking=no pureuser@flasharray1 "purearray rename {{ New_Name }}"
    register: op
    ignore_errors: true
  - debug:
      var: op
  - set_fact:
      status_code: 2
      response_message: "{{ op.stderr }}"
    when: op is failed
  - set_fact:
      response_message: "Pure renamed to {{ New_Name }}\n{{ op.stdout }}"
    when: op is success

  
  - name: Gather capacity report
    shell: sshpass -p "pureuser" ssh -o StrictHostKeyChecking=no pureuser@flasharray1 "purearray list"
    register: ops
    ignore_errors: true
  - debug:
      var: ops
  - set_fact:
      status_code: 2
      response_message: "{{ ops.stderr }}"
    when: ops is failed
  - set_fact:
      response_message: "Pure renamed to {{ New_Name }}\n{{ ops.stdout }}"
    when: ops is success

