---
# tasks file for Pure_Storage_Utilization_Trends
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Pure storage usage trends
    shell: sshpass -p "pureuser" ssh -o StrictHostKeyChecking=no pureuser@flasharray1 "purearray list --space --historical 30d"
    register: op
    ignore_errors: true
  - debug:
      var: op
  - set_fact:
      status_code: 2
      response_message: "Error encountered: \n {{ op.stderr }}"
    when: op is failed
  - set_fact:
      response_message: "{{ op.stdout }}"
    when: op is success
  - debug:
      var: response_message
